name: "aibomgen-cli Action"
description: "Downloads aibomgen-cli (a Go CLI tool) to the Action tool cache and provides a command reference"
author: "IDLab Discover"

inputs:
  command:
    required: true
    description: "The action command to run"
    default: "download"

  aibomgen-version:
    required: false
    description: "The version of aibomgen-cli to download (for example v0.2.1). Defaults to the bundled version."

outputs:
  cmd:
    description: "A reference to the aibomgen-cli command"

runs:
  using: "node20"
  main: "../dist/index.cjs"
